/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113568-gcd31eac999-20240208"
#endif /* AVUTIL_FFVERSION_H */
