/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113523-g7375a6ca7b-20240204"
#endif /* AVUTIL_FFVERSION_H */
